services:
  # Docker 배포 서비스
  - name: cvfactory
    type: web
    env: docker
    dockerfilePath: ./Dockerfile.prod
    dockerContext: .
    envVars:
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: cvfactory.onrender.com,localhost,127.0.0.1
      - key: CSRF_TRUSTED_ORIGINS
        value: https://cvfactory.onrender.com,http://localhost:8000
      - key: CORS_ALLOWED_ORIGINS
        value: https://cvfactory.onrender.com,http://localhost:8000
      - key: RENDER
        value: true
      - key: RENDER_EXTERNAL_HOSTNAME
        value: cvfactory.onrender.com
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.9.21
      - key: DATABASE_URL
        fromDatabase:
          name: cvfactory-db
          property: connectionString
    healthCheckPath: /api/health/
    plan: free

databases:
  - name: cvfactory-db
    databaseName: cvfactory
    user: cvfactory
    plan: free 