service: cvfactory

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-northeast-2'}
  environment:
    STAGE: ${self:provider.stage}
    DJANGO_SECRET_KEY: ${env:DJANGO_SECRET_KEY}
    ALLOWED_HOSTS: ${env:ALLOWED_HOSTS}
    DEBUG: ${env:DEBUG, 'false'}
    GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID}
    GOOGLE_CLIENT_SECRET: ${env:GOOGLE_CLIENT_SECRET}
    GROQ_API_KEY: ${env:GROQ_API_KEY}
    API_KEY: ${env:API_KEY}
    CSRF_TRUSTED_ORIGINS: ${env:CSRF_TRUSTED_ORIGINS}
    CORS_ALLOWED_ORIGINS: ${env:CORS_ALLOWED_ORIGINS}
  
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource: !GetAtt [StaticBucket, Arn]

package:
  patterns:
    - '!.git/**'
    - '!.github/**'
    - '!.env*'
    - '!node_modules/**'
    - '!tests/**'
    - '!README.md'
    - '!*.sh'
    - '!.gitignore'
    - '!Dockerfile'
    - '!docker-compose.yml'

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'
    environment:
      LOG_LEVEL: ${env:LOG_LEVEL, 'INFO'}
    timeout: 30
    memorySize: 1024

custom:
  pythonRequirements:
    dockerizePip: true
    usePoetry: false
    slim: true
    layer: true

  wsgi:
    app: cvfactory.wsgi.application
    packRequirements: false

  customDomain:
    domainName: ${env:DOMAIN_NAME, ''}
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: 'regional'
    securityPolicy: tls_1_2
    apiType: http
    autoDomain: true

resources:
  Resources:
    StaticBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: cvfactory-static-${self:provider.stage}
        AccessControl: PublicRead
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
              AllowedOrigins:
                - '*'

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-domain-manager 