name: CVFactory CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:  # 수동 실행 옵션

# 권한 설정 추가
permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.18'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Set environment based on branch
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "Setting production environment"
            cp .env.example .env
            echo "DEBUG=False" >> .env
            echo "TEST_MODE=True" >> .env
            echo "DB_ENGINE=django.db.backends.sqlite3" >> .env
            echo "DB_NAME=:memory:" >> .env
          else
            echo "Setting development environment"
            cp .env.example .env
            echo "DEBUG=True" >> .env
            echo "TEST_MODE=True" >> .env
            echo "DB_ENGINE=django.db.backends.sqlite3" >> .env
            echo "DB_NAME=:memory:" >> .env
          fi
          
          # 환경 변수 내용 로깅 (민감 정보 제외)
          echo "Environment configuration:"
          grep -v "SECRET\|KEY\|PASSWORD" .env || true
      
      - name: Create logs directory with proper permissions
        run: |
          mkdir -p logs
          chmod -R 755 logs
      
      - name: Database setup
        run: |
          echo "Setting up database for tests..."
          python manage.py check
          python manage.py makemigrations --check --dry-run
          python manage.py migrate --noinput
          
      - name: Run tests with detailed logging
        run: |
          echo "Running Django tests..."
          
          # 앱 리스트 가져오기
          APPS=$(python -c "
          import os
          import sys
          
          # Django 설정 로드
          os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'cvfactory.settings')
          
          import django
          django.setup()
          
          # 설치된 앱 목록 출력
          from django.conf import settings
          for app in settings.INSTALLED_APPS:
              if not app.startswith('django.') and not app.startswith('rest_framework'):
                  print(app)
          ")
          
          echo "Installed apps: $APPS"
          
          # 먼저 전체 테스트 실행
          python manage.py test -v 2 || true
          
          # 실패한 경우 앱별로 테스트 실행해 문제 파악
          for app in $APPS; do
            echo "Testing app: $app"
            python manage.py test $app -v 2 || echo "App $app tests failed"
          done
  
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.18'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Set environment based on branch
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "Setting production environment"
            cp .env.example .env
            # 배포 환경에서는 실제 API 키 등을 GitHub Secrets에서 가져와 설정
            echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env
            echo "ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}" >> .env
            echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
            echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
            echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" >> .env
            echo "API_KEY=${{ secrets.API_KEY }}" >> .env
            echo "CSRF_TRUSTED_ORIGINS=${{ secrets.CSRF_TRUSTED_ORIGINS }}" >> .env
            echo "CORS_ALLOWED_ORIGINS=${{ secrets.CORS_ALLOWED_ORIGINS }}" >> .env
            echo "DEBUG=False" >> .env
          else
            echo "Setting development environment"
            cp .env.example .env
            echo "DJANGO_SECRET_KEY=${{ secrets.DEV_DJANGO_SECRET_KEY }}" >> .env
            echo "ALLOWED_HOSTS=${{ secrets.DEV_ALLOWED_HOSTS }}" >> .env
            echo "DEBUG=True" >> .env
            # 개발 환경 설정
            echo "GOOGLE_CLIENT_ID=dummy-dev-client-id" >> .env
            echo "GOOGLE_CLIENT_SECRET=dummy-dev-client-secret" >> .env
            echo "GROQ_API_KEY=dummy-dev-groq-api-key" >> .env
          fi
      
      - name: Collect static files
        run: python manage.py collectstatic --noinput
      
      - name: Run migrations
        run: python manage.py migrate --noinput
      
      - name: Create logs directory with proper permissions
        run: |
          mkdir -p logs
          chmod -R 755 logs
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            .
            !.git
            !.github
  
  deploy-dev:
    if: github.ref == 'refs/heads/develop'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: .
      
      - name: Deploy to Render.com Development Environment
        uses: JorgeLNJunior/render-deploy@v1.4.3
        with:
          service_id: ${{ secrets.RENDER_DEV_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait: true
  
  deploy-prod:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: .
      
      - name: Deploy to Render.com Production Environment
        uses: JorgeLNJunior/render-deploy@v1.4.3
        with:
          service_id: ${{ secrets.RENDER_PROD_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait: true 
  
  notify:
    needs: [test, build, deploy-prod, deploy-dev]
    runs-on: ubuntu-latest
    if: always()  # 항상 실행
    steps:
      - name: Check workflow status
        id: status
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" ]]; then
            echo "workflow_status=failure" >> $GITHUB_OUTPUT
          else
            echo "workflow_status=success" >> $GITHUB_OUTPUT
          fi
      
      - name: Notify workflow status
        if: steps.status.outputs.workflow_status == 'failure'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { repo, owner } = context.repo;
            const run_id = context.runId;
            
            try {
              await github.rest.issues.create({
                owner,
                repo,
                title: `🚨 워크플로우 실패: ${context.workflow}`,
                body: `**워크플로우가 실패했습니다.**
                
                - **저장소:** ${owner}/${repo}
                - **워크플로우:** ${context.workflow}
                - **커밋:** ${context.sha}
                - **브랜치:** ${context.ref}
                - **상세 정보:** https://github.com/${owner}/${repo}/actions/runs/${run_id}
                
                이 이슈는 자동으로 생성되었습니다.`
              });
              console.log('알림 이슈가 성공적으로 생성되었습니다.');
            } catch (error) {
              console.error('이슈 생성 중 오류 발생:', error);
              // 이슈 생성 실패시 워크플로우 진행을 위한 예외 처리
              return; 
            } 